### ISSUE TITLE
Feed APIs (Read Only)

### ISSUE THREAD

**Issue by islam-kamel** [islam-kamel/ArabClub#20]
#News Feed Microservices

Create Microservices to GET all feed from database and feet details

allow only `GET` Method

ex. Urls endpoint
```
GET Feed/
GET Feed/post_id
```

**Comment by ntsagar9** [comment]
Let check the code. I would like to help you.

**Comment by islam-kamel** [comment]
Of course I do. 🧑‍💻

**Comment by islam-kamel** [comment]
Remember you answer to work through a branch `microservices`

**Comment by islam-kamel** [comment]
You can send me a message on slack `islam.kamel` if you need

**Comment by ntsagar9** [comment]
Hi not able to docker-compose build because **microservices** don't have Dcokerfile in django_client folder.

**Comment by islam-kamel** [comment]
Don't do this right now. It's not ready. Just work through Python's server.

**Comment by islam-kamel** [comment]
```
cd django_restfull 
mkdir fees_read_api
start from here
```

**Comment by islam-kamel** [comment]
look in `django_restfull\archive\newsfeed`

**Comment by ntsagar9** [comment]
Will check.
