### ISSUE TITLE
Feed APIs (Write only)

### ISSUE THREAD

**Issue by islam-kamel** [islam-kamel/ArabClub#21]
#News Feed Microservices

Create Microservices to Create new post , update post and delete post

allow only `POST` `PUT` `DELETE` Method

ex. Urls endpoint
```
POST     Feed/
PUT      Feed/post_id
DELETE   Feed/post_id
```

**Comment by hrittik2002** [comment]
have to do this in javascript?

**Comment by islam-kamel** [comment]
Django

**Comment by hrittik2002** [comment]
oh okkk
